import { Controller, Get, Req } from '@nestjs/common';
import { ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { Request } from 'express';

@ApiTags('Lab 2 – Patrones')
@Controller('lab2/middleware')
export class MiddlewareController {
  @Get('request-id')
  @ApiOperation({ summary: 'Returns the X-Request-Id injected by RequestIdMiddleware into the request' })
  @ApiResponse({ status: 200 })
  requestId(@Req() req: Request) {
    return {
      data: {
        requestId: req.headers['x-request-id'],
        note: 'UUID generated by RequestIdMiddleware per request — also set as response header',
      },
    };
  }

  @Get('logged')
  @ApiOperation({ summary: 'Returns { logged: true } — check server console for the middleware log line' })
  @ApiResponse({ status: 200 })
  logged() {
    return { data: { logged: true } };
  }
}
